### ISSUE TITLE
Rename to `eslint-config-callstack`?

### ISSUE THREAD

**Issue by thymikee** [callstack/eslint-config-callstack#16]
Or should we wait for scoped `@callstack/eslint-config`?

**Comment by thymikee** [comment]
cc: @satya164 @jukben @ferrannp

**Comment by jukben** [comment]
I like the `@callstack/eslint-config` and as far I know @grabbou is also for that.

Why should we wait?

**Comment by grabbou** [comment]
Shall we do something about this issue? 👯‍♂️
