### ISSUE TITLE
There is a deprecated piece of a suggestion

### ISSUE THREAD

**Issue by rezkiy37** [callstack/eslint-config-callstack#263]
## Environment

MacOS + VSCode

## Description

[The last step](https://github.com/callstack/eslint-config-callstack) of the installation guide recommends to add addition settings for VSCode. Looks like it is already a little bit deprecated.

### Initial warning
<img width="500" alt="Screenshot 2023-06-05 at 15 19 17" src="https://github.com/callstack/eslint-config-callstack/assets/57314631/6aad2752-9844-4289-846d-d1e9e9c94f87">

### Fix
<img width="500" alt="Screenshot 2023-06-05 at 15 19 01" src="https://github.com/callstack/eslint-config-callstack/assets/57314631/95c4b209-c46b-4727-9a94-013614f752fc">

**Comment by thymikee** [comment]
PR appreciated!

**Comment by rezkiy37** [comment]
> PR welcome and appreciated!

Good, I will open one. Thank you!
