### ISSUE TITLE
Lack of support for flat config (default starting in ESLint v9.0.0)

### ISSUE THREAD

**Issue by artus9033** [callstack/eslint-config-callstack#276]
## Environment

ESLint $\geqslant 9.0.0$
`@callstack/eslint-config` `^14.2.0`

## Description

The config does not work since it does not use [flat config](https://eslint.org/docs/latest/use/migrate-to-9.0.0#flat-config), which is the default since ESLint v9.0.0.

It can be [worked around](https://eslint.org/blog/2023/11/whats-coming-in-eslint-9.0.0/#flat-config-now-the-default-and-has-some-changes) by setting the env var `ESLINT_USE_FLAT_CONFIG=false`, yet it would be good to support the new format, also having backwards-compatible (eslintrc-style) configuration exports.

## Reproducible Demo

Upgrade ESLint to $\geqslant 9.0.0$ in any project using `eslint-config-callstack` and run ESLint.

**Comment by marcinkornek** [comment]
@artus9033 library supports ESLint flat config since version 15.0.0 https://github.com/callstack/eslint-config-callstack/releases/tag/v15.0.0

**Comment by artus9033** [comment]
Hey, thanks @marcinkornek & @thymikee ! I must've forgotten about tagging this one in the PR.
