### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by jukben** [callstack/eslint-config-callstack#31]
I've built my own personal config based on this one. 

Someone can take it, just replace the rules and it should be ready to go.

https://github.com/jukben/eslint-config

For instance we don't need eslint-restricted-globals – it's already in eslint-config-airbnb-base,...

**Comment by thymikee** [comment]
anybody willing to backport the changes? :)

**Comment by jukben** [comment]
It can be done as part #30 Wdyt @ferrannp ?

**Comment by thymikee** [comment]
yup, thanks @jukben
