### ISSUE TITLE
CRA: Incompatible version of babel-eslint

### ISSUE THREAD

**Issue by zamotany** [callstack/eslint-config-callstack#34]
Our config is using `babel-eslint@8.2.6`, but newer CRA is installing version `9.0.0` so when running `react-scripts start` the user is greeted with this _nice_ error:

![screen shot 2018-10-16 at 12 03 53](https://user-images.githubusercontent.com/17573635/47008954-96518280-d13b-11e8-95c3-eeb2f1168381.png)

The question is should we do anything with it? Maybe bump `babel-eslint`??

**Comment by thymikee** [comment]
Yup, bump it 👍

**Comment by thymikee** [comment]
Updated to v10
