### ISSUE TITLE
Typescript & VSCode

### ISSUE THREAD

**Issue by grabbou** [callstack/eslint-config-callstack#55]
There's few additional steps needed to make this run inside VSCode - might be a good idea to mention the following need to be added to `settings.json`:

```
{
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    {"language": "typescript", "autoFix": true },
    {"language": "typescriptreact", "autoFix": true }
  ]
}
```

**Comment by grabbou** [comment]
Probably we should also add `plugin:import/typescript` to get rid of `no-unresolved` errors when importing `tsx` files.

**Comment by thymikee** [comment]
@grabbou send a PR please :)

**Comment by grabbou** [comment]
Unfortunately, I don't have time to do it anytime soon. Leaving this issue here mainly as a pointer to other engineers that might be struggling to get this up and running in their environments.

CC: @zamotany as you have authored TypeScript support in the readme, what do you think about the list of above steps I mentioned? Did you have to do them on your own too?
