### ISSUE TITLE
Prettier 2 bump

### ISSUE THREAD

**Issue by rdy** [callstack/eslint-config-callstack#93]
In order to take advantage of some new features with typescript 3.8 it would be great to bump to prettier 2 which was recently released. 

I can try to see how this effects some code bases already using this eslint-config.

**Comment by thymikee** [comment]
Agreed, we have plans to do so. Want to tackle the bump? :)

**Comment by rdy** [comment]
Yes, I'll setup a PR and see how it goes.

**Comment by rdy** [comment]
check our PR #96 this worked fine for our repos that are reliant on this configuration

**Comment by thymikee** [comment]
Closed via #96
