### ISSUE TITLE
RFC: sort imports by default

### ISSUE THREAD

**Issue by thymikee** [callstack/eslint-config-callstack#98]
## Describe the feature

Deterministic imports are nice to have, what do you think about including this plugin by default? It's like Prettier, but for import order.

https://github.com/lydell/eslint-plugin-simple-import-sort

## Motivation

Fixable, deterministic import ordering.

**Comment by zamotany** [comment]
Why `eslint-plugin-simple-import-sort`, we already use `eslint-plugin-import` which allows sorting: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md

**Comment by thymikee** [comment]
Good point @zamotany. We should enable it by default then

**Comment by NoemiRozpara** [comment]
I don't know much about the possible solutions, but would be happy for such option turned on by default. Usually I tried to use some prettier setting, but had a lot of issues with prettier in general, so was ending up with no auto order for my imports ¯\_(ツ)_/¯

**Comment by thymikee** [comment]
Let's do it with `eslint-plugin-import` `order` rule as @zamotany noted.
